# -*- coding: utf-8 -*-
"""text_davinci_002_t2i.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1OhpXTVf1IYukP5VsGPchqSTfauZ3KEUA

# OPEN API
"""

!pip install openai

OPENAPI_KEY = '' # Input your APIKey
USE_ENGINE = 'text-davinci-002'
# USE_ENGINE = 'text-davinci-003'

import openai

class AIChat:
  def __init__(self):
    openai.api_key = OPENAPI_KEY

  def response(self, user_input):
    response = openai.Completion.create(
        engine=USE_ENGINE,
        prompt=user_input,
        max_tokens=1024,
        temperature=0.5
    )

    # 応答のテキスト部分を取得して返す
    return response['choices'][0]['text']

def main():
  chatai = AIChat()

  print('>> Hello I\'m ChatAI\'')
  print('>> if input [q] is quit')

  while True:
    user_input = input('>> User: ')
    # user_input = 'How to install Python'

    if user_input == 'q':
      break

    # Get response fot ChatAI
    response = chatai.response(user_input)
    print(f'>> AIChat: {response}')
    print('\n')
  print('>> AIChat: GoodBye')

if __name__ == '__main__':
  main()